name: gd4js
title: gd4js
description: My JavaScript Deobfuscator and Unpacker
version: 1.12.0
author: Dev Chandel
author_email: dev@gmail.com
url: https://goojdex.github.io
baseurl: /gd4js
repository: GoojDex/gd4js
license: MIT

theme: jekyll-theme-hacker
show_downloads: false
google_analytics: UA-00000-1
sass:
  style: compressed

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "package.json",
    "package-lock.json",
    "Dockerfile",
    "docker-compose.yml",
    "docker-entrypoint.sh",
    "workbox-config.js"
  ]
incremental: false

environment: production
